name: Compile Latex and Release PDF

on:
  push:
    branches:
      - master
    
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: report
          root_file: main.tex

      - name: Release
        id: release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: release-${{ github.run_id }}-${{ github.run_number }}
          release_name: Release ${{ github.run_id }}-${{ github.run_number }}
          draft: false
          prerelease: false


      - name: Upload
        id: upload
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: ./report/main.pdf
          asset_name: main.pdf
          asset_content_type: application/pdf
